import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { aiEnabled, generatePractice, type GeneratedProblem } from '../lib/ai'
import { CONCEPTS, type ConceptId } from '../lib/physics'
import { CONCEPT_COLOR } from '../lib/practiceConcepts'
import { toBarDragStep } from '../lib/practiceProblem'
import { BarDragStepView } from './steps/BarDragStepView'

type Props = {
  conceptId: ConceptId
}

/**
 * Feature 1: never-ending practice for one concept. Every problem's parameters
 * and answer are produced/verified by the physics core; the AI only supplies the
 * scenario wording (with a deterministic fallback when AI is off).
 */
export function PracticeSession({ conceptId }: Props) {
  const concept = CONCEPTS[conceptId]
  const [problem, setProblem] = useState<GeneratedProblem | null>(null)
  const [loading, setLoading] = useState(true)
  const [keyN, setKeyN] = useState(0)
  const [solvedCount, setSolvedCount] = useState(0)

  const load = useCallback(async () => {
    setLoading(true)
    const next = await generatePractice(conceptId, 'medium')
    setProblem(next)
    setKeyN((k) => k + 1)
    setLoading(false)
  }, [conceptId])

  useEffect(() => {
    void load()
  }, [load])

  const step = problem ? toBarDragStep(problem) : null

  return (
    <div className="practice">
      <header className="practice__header">
        <Link to="/" className="practice__back">
          ← Done
        </Link>
        <div className="practice__title-block">
          <span className="practice__eyebrow">Infinite practice</span>
          <h1 className="practice__title" style={{ color: CONCEPT_COLOR[conceptId] }}>
            {concept.name}
          </h1>
        </div>
        <span className="practice__count" title="Problems solved this session">
          {solvedCount} solved
        </span>
      </header>

      {!aiEnabled && (
        <p className="practice__note">
          Running offline — problems are generated by the physics engine.
        </p>
      )}

      {loading || !step ? (
        <div className="practice__loading">
          <span className="practice__spinner" />
          <span>Generating a fresh problem…</span>
        </div>
      ) : (
        <div className="practice__card">
          <BarDragStepView
            key={keyN}
            step={step}
            draft={null}
            onDraftChange={() => {}}
            onCorrect={() => void load()}
            onAttempt={(_answer, correct) => {
              if (correct) setSolvedCount((n) => n + 1)
            }}
          />
        </div>
      )}
    </div>
  )
}
